# -*- coding: utf-8 -*-
"""Python Basics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VyvAlerFvuiLvH7U60KhhbJSafkLyB6H

# Curso: "Python para Data Science: Primeiros Passos."

##*Coleta e amostragem de dados*

### 1. Crie um programa que solicite à pessoa usuária digitar seu nome, e imprima “Olá, [nome]!”.
"""

name = input('Inserch your name:\n');
Name = name.title();

print(f'Hello {Name}');

"""###2. Crie um programa que solicite à pessoa usuária digitar seu nome e idade, e imprima “Olá, [nome], você tem [idade] anos.”."""

name = input('Inserch your name:\n');
Name = name.title();

Age = int(input('Inserch your age:\n'));

print(f'Hello {Name}, you are {Age} years old.');

"""###3. Crie um programa que solicite à pessoa usuária digitar seu nome, idade e altura em metros, e imprima “Olá, [nome], você tem [idade] anos e mede [altura] metros!”."""

name = input("Inserch your name: ");
Name = name.title();

Age = int(input("Inserch your age: "));

Height = float(input("Inserch your height in meters: "));

print(f'Hello {Name}, you are {Age} years old and {Height} meters tall.');

"""##Calculadora com operadores

###1.Crie um programa que solicite dois valores numéricos à pessoa usuária e imprima a soma dos dois valores.
"""

n1 = float(input("Inserch a number: "));
n2 = float(input("inserch another one: "));

x = n1 + n2;

print(f'The sum of {n1} and {n2} is = {x}');

"""###2. Crie um programa que solicite três valores numéricos à pessoa usuária e imprima a soma dos três valores.

"""

n1 = float(input('Inserch the first number: '));
n2 = float(input('Inserch the second number: '));
n3 = float(input('Inserch the third number: '));

x = n1 + n2 + n3;

print(f'The sum of {n1}, {n2} and {n3} is = {x:.2f}');

"""###3. Crie um programa que solicite dois valores numéricos à pessoa usuária e imprima a subtração do primeiro pelo o segundo valor.

"""

n1 = float(input('Inserch a number: '));
n2 = float(input('Inserch another one: '));

x = n1 - n2;

print(f"The numbers subtraction is: {x:.2f}");

"""###4. Crie um programa que solicite dois valores numéricos à pessoa usuária e imprima a multiplicação dos dois valores.

"""

n1 = float(input('Inserch a number: '));
n2 = float(input('Inserch another one: '));

x = n1*n2;

print(f"The numbers multiplication is: {x:.2f}");

"""###5. Crie um programa que solicite dois valores numéricos, um numerador e um denominador, e realize a divisão entre os dois valores. Deixe claro que o valor do denominador não pode ser 0.

"""

n1 = float(input('Inserch a numer for the numerator: '));
n2 = float(input('Inserch a number, but zero, for the denominator: '));

x = n1/n2;

print(f"The numbers division is: {x:.2f}");

"""###6. Crie um programa que solicite dois valores numéricos, um operador e uma potência, e realize a exponenciação entre esses dois valores.

"""

n1 = float(input('Inserch a operator number: '));
n2 = float(input('Inserch a potential number: '));

x = n1**n2;

print(f"The result for operator {n1} with {n2} potential is: {x:.2f}");

"""###7. Crie um programa que solicite dois valores numéricos, um numerador e um denominador e realize a divisão inteira entre os dois valores. Deixe claro que o valor do denominador não pode ser 0.

"""

n1 = float(input('Inserch a numerator number: '));
n2 = float(input('Inserch a denominator number, but zero: '));

x = n1//n2;

print(f"The entire part is: {x}");

"""###8. Crie um programa que solicite dois valores numéricos, um numerador e um denominador, e retorne o resto da divisão entre os dois valores. Deixe claro que o valor do denominador não pode ser 0.

"""

n1 = float(input('Inserch a numerator: '));
n2 = float(input('Inserch a denominator, but zero: '));

x = n1%n2;

print(f"The rest is: {x}");

"""###9. Crie um código que solicita 3 notas de um estudante e imprima a média das notas.

"""

m = float(input('Inserch your math grade: '));
p = float(input('Inserch your portuguese grade: '));
h = float(input('Inserch your history grade: '));

md = (m+p+h)/3;

print(f"Your mouth avarege is: {md:.2f}");

"""###10. Crie um código que calcule e imprima a média ponderada dos números 5, 12, 20 e 15 com pesos respectivamente iguais a 1, 2, 3 e 4.

"""

x = ((1*5) + (2*12) + (3*20) + (4*15))/4

print(f'The weighted avarage is {x}');

"""##Editando textos

###1. Crie uma variável chamada “frase” e atribua a ela uma string de sua escolha. Em seguida, imprima a frase na tela.
"""

frase = 'Hi, my name is Maria and this is my training.'

print(frase);

"""###2. Crie um código que solicite uma frase e depois imprima a frase na tela.

"""

frase = input('Now I am a raven, say somwthing and I will say it the same way: ');

print(frase);

"""###3. Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase digitada mas com todas as letras maiúsculas.

"""

frase = input('Now you can say anithing out loud, I just whisper it: ');

x = frase.lower();

print(x);

"""###4. Crie uma variável chamada “frase” e atribua a ela uma string de sua escolha. Em seguida, imprima a frase sem espaços em branco no início e no fim.

"""

frase = "Maybe, maybe, I am trying to do something different.  ";

x = frase.replace("Maybe,", "");

w = x.strip();

y = w[0].upper() + w[1:];

print(y);

"""###5. Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase sem espaços em branco no início e no fim.

"""

frase = input("Write a phrase: ");

frase = frase.strip();

print(frase);

"""###6. Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase sem espaços em branco no início e no fim e em letras minúsculas.

"""

frase = input("Write a phrase:");

x = frase.strip();

y = x.lower();

print(y);

"""###7. Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase com todas as vogais “e” trocadas pela letra “f”.

"""

frase = input("Write something with 'e' and see the magic happends: ");

x = frase.replace("e", "f").replace("E","F");

print(x);

"""###8. Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase com todas as vogais “a” trocadas pela caractere “@”.

"""

frase = input("I'm becaming creative, write something with 'a': ");

x = frase.replace("A","@").replace("a", "@");

print(x);

"""###9. Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase com todas as consoantes “s” trocadas pelo caractere “$”.

"""

frase = input("If you wore rich (don't look at me like that) every 's' would have '$' insted, right? ");

x = frase.replace("S","$").replace("s","$");

print(x);

